# Утилиты

In [1]:
import numpy as np
from scipy.stats import (
    norm,
    chi2,
    ranksums,  # Критерий Вилкоксона для независимых выборок
    wilcoxon,  # Критерий Вилкоксона для зависимых выборок
    friedmanchisquare,  # Критерий Фридмана
    kruskal,  # Критерий Краскела-Уоллиса
    median_test,  # Медианный тест
)
from typing import Tuple
import pandas as pd

In [2]:
def calculate_p_value(statistics: float, *, distribution, alternative: str, **kwargs) -> float:
    right_tail_p_value = distribution.sf(statistics, **kwargs)
    left_tail_p_value = distribution.cdf(statistics, **kwargs)  
    two_sided_p_value = 2 * min(left_tail_p_value, right_tail_p_value)

    if alternative == 'less':
        p_value = left_tail_p_value
    elif alternative == 'greater':
        p_value = right_tail_p_value
    else:
        p_value = two_sided_p_value

    return p_value

In [3]:
def rankdata(x: np.ndarray) -> np.ndarray:
    sorted_x = np.sort(x)
    ranks = np.arange(len(sorted_x), dtype=float) + 1

    value_to_count = dict(zip(*np.unique(sorted_x, return_counts=True)))

    value_to_rank = {}
    for value, count in value_to_count.items():
        left = np.searchsorted(sorted_x, value, side='left')
        right = np.searchsorted(sorted_x, value, side='right')
        value_to_rank[value] = ranks[left:right].sum() / count

    return np.array([value_to_rank[value] for value in x])

In [4]:
addicts_data = pd.read_excel('addicts0.xls', sheet_name=1)
addicts_data

prcod 
 intpla 
 sex 
 age 
 educat 
 curwor 
 asi1_med 
 asi2_emp 
 asi3_alc 
 asi4_dr 
 ... 
 ha 
 se 
 cravin 
 rabdru 
 rubsex 
 gaf 
 bdi 
 sstati 
 end 
 endpo 
 
 
 
 
 0 
 4 
 1 
 0 
 18 
 1 
 1 
 0.19 
 0.70 
 0.120 
 0.30 
 ... 
 1.0 
 0.0 
 4.6 
 1.0 
 4 
 55.0 
 25.0 
 60 
 0.0 
 5.0 
 
 
 1 
 2 
 2 
 1 
 30 
 4 
 1 
 0.44 
 0.23 
 0.006 
 0.27 
 ... 
 0.0 
 0.0 
 9.7 
 4.0 
 5 
 55.0 
 39.0 
 50 
 0.0 
 5.0 
 
 
 2 
 2 
 1 
 0 
 23 
 2 
 0 
 0.50 
 1.00 
 0.300 
 0.30 
 ... 
 0.0 
 0.0 
 9.5 
 6.0 
 1 
 45.0 
 29.0 
 55 
 0.0 
 2.0 
 
 
 3 
 4 
 1 
 0 
 20 
 2 
 1 
 0.00 
 0.80 
 0.050 
 0.26 
 ... 
 1.0 
 0.0 
 2.7 
 11.0 
 4 
 40.0 
 28.0 
 58 
 0.0 
 5.0 
 
 
 4 
 3 
 2 
 0 
 20 
 2 
 0 
 0.00 
 0.75 
 0.780 
 0.23 
 ... 
 0.0 
 0.0 
 3.0 
 19.0 
 4 
 40.0 
 28.0 
 58 
 0.0 
 2.0 
 
 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 
 
 275 
 1 
 2 
 0 
 23 
 2 
 0 
 0.10 
 0.59 
 0.000 
 0.25 
 ... 
 1.0 
 0.0 
 4.5 
 5.0 
 2 
 41.0 
 17.0 
 47 
 0.0 
 2.0 
 
 
 276 
 4 
 2 
 0 
 25 
 2 
 0 
 0.00 
 1.00 
 0.000 
 0.25 
 ... 
 1.0 
 0.0 
 0.8 
 6.0 
 6 
 50.0 
 21.0 
 45 
 0.0 
 2.0 
 
 
 277 
 1 
 2 
 0 
 24 
 2 
 0 
 0.00 
 1.00 
 0.210 
 0.21 
 ... 
 0.0 
 1.0 
 1.5 
 8.0 
 5 
 50.0 
 12.0 
 40 
 1.0 
 1.0 
 
 
 278 
 1 
 2 
 1 
 18 
 2 
 0 
 0.00 
 1.00 
 0.020 
 0.29 
 ... 
 0.0 
 1.0 
 4.0 
 14.0 
 5 
 45.0 
 22.0 
 62 
 0.0 
 5.0 
 
 
 279 
 3 
 1 
 0 
 28 
 2 
 0 
 0.40 
 1.00 
 0.120 
 0.30 
 ... 
 0.0 
 0.0 
 10.0 
 10.0 
 5 
 48.0 
 26.0 
 62 
 1.0 
 1.0 
 
 
 
 280 rows × 27 columns

In [5]:
alcohol_data = pd.read_csv('data_big.csv', index_col=0)
alcohol_data

X.1 
 depressed.mood.1 
 anxiety.1 
 suspiciousness.1 
 irritability.1 
 craving.to.alcohol.1 
 weakness.1 
 insomia.1 
 headache.1 
 tremor.1 
 ... 
 combined2.9 
 HR.9 
 SBP.9 
 DBP.9 
 MBP.9 
 SV.9 
 CO.9 
 SI.9 
 CI.9 
 TPR.9 
 
 
 
 
 1 
 1 
 1 
 1 
 0 
 1 
 1 
 1 
 1 
 0 
 1 
 ... 
 0 
 68.0 
 108.0 
 70.0 
 83.0 
 74.0 
 5.0 
 40.0 
 2.7 
 1321.0 
 
 
 2 
 2 
 1 
 1 
 0 
 0 
 1 
 1 
 2 
 1 
 1 
 ... 
 9 
 63.0 
 114.0 
 70.0 
 85.0 
 123.0 
 7.7 
 60.0 
 3.8 
 879.0 
 
 
 3 
 3 
 1 
 1 
 0 
 0 
 0 
 2 
 1 
 0 
 2 
 ... 
 0 
 64.0 
 120.0 
 80.0 
 93.0 
 106.0 
 6.8 
 55.0 
 3.5 
 1098.0 
 
 
 4 
 4 
 2 
 2 
 0 
 0 
 0 
 2 
 0 
 0 
 1 
 ... 
 0 
 56.0 
 124.0 
 90.0 
 101.0 
 90.0 
 5.1 
 43.0 
 2.4 
 1600.0 
 
 
 5 
 5 
 1 
 1 
 0 
 0 
 2 
 2 
 1 
 0 
 1 
 ... 
 0 
 66.0 
 116.0 
 78.0 
 90.0 
 90.0 
 5.9 
 45.0 
 2.2 
 1228.0 
 
 
 6 
 6 
 1 
 1 
 0 
 1 
 1 
 2 
 0 
 0 
 2 
 ... 
 0 
 62.0 
 142.0 
 90.0 
 107.0 
 113.0 
 7.0 
 56.0 
 3.4 
 1225.0 
 
 
 7 
 7 
 1 
 1 
 0 
 1 
 1 
 2 
 2 
 1 
 1 
 ... 
 0 
 85.0 
 110.0 
 84.0 
 93.0 
 46.0 
 3.9 
 21.0 
 1.8 
 1899.0 
 
 
 8 
 8 
 1 
 1 
 0 
 1 
 0 
 1 
 2 
 1 
 1 
 ... 
 0 
 68.0 
 134.0 
 88.0 
 103.0 
 74.0 
 6.4 
 33.0 
 2.9 
 1290.0 
 
 
 9 
 9 
 1 
 1 
 0 
 0 
 2 
 1 
 0 
 0 
 1 
 ... 
 0 
 76.0 
 134.0 
 76.0 
 96.0 
 116.0 
 8.6 
 60.0 
 4.4 
 886.0 
 
 
 10 
 10 
 1 
 1 
 0 
 1 
 1 
 1 
 2 
 1 
 1 
 ... 
 0 
 64.0 
 110.0 
 70.0 
 83.0 
 43.0 
 2.7 
 27.0 
 1.7 
 2467.0 
 
 
 11 
 11 
 1 
 1 
 0 
 1 
 1 
 1 
 1 
 0 
 1 
 ... 
 0 
 83.0 
 124.0 
 76.0 
 92.0 
 59.0 
 4.9 
 30.0 
 2.6 
 1500.0 
 
 
 12 
 12 
 1 
 1 
 0 
 1 
 1 
 2 
 0 
 1 
 1 
 ... 
 0 
 50.0 
 118.0 
 70.0 
 86.0 
 130.0 
 6.5 
 69.0 
 3.5 
 1057.0 
 
 
 13 
 13 
 1 
 1 
 0 
 1 
 1 
 2 
 2 
 0 
 1 
 ... 
 2 
 66.0 
 110.0 
 70.0 
 83.0 
 106.0 
 7.0 
 56.0 
 3.7 
 942.0 
 
 
 14 
 14 
 1 
 1 
 0 
 0 
 2 
 2 
 2 
 0 
 1 
 ... 
 2 
 64.0 
 140.0 
 84.0 
 103.0 
 124.0 
 7.9 
 69.0 
 4.4 
 1039.0 
 
 
 15 
 15 
 1 
 1 
 0 
 1 
 1 
 2 
 1 
 0 
 2 
 ... 
 0 
 84.0 
 114.0 
 84.0 
 94.0 
 69.0 
 6.0 
 41.0 
 3.6 
 1256.0 
 
 
 16 
 16 
 1 
 1 
 0 
 0 
 1 
 1 
 2 
 0 
 1 
 ... 
 0 
 74.0 
 100.0 
 70.0 
 80.0 
 74.0 
 5.5 
 44.0 
 3.2 
 1162.0 
 
 
 17 
 17 
 1 
 1 
 0 
 0 
 1 
 2 
 1 
 0 
 1 
 ... 
 0 
 68.0 
 114.0 
 76.0 
 88.0 
 63.0 
 4.3 
 34.0 
 2.3 
 1649.0 
 
 
 18 
 18 
 1 
 1 
 0 
 0 
 0 
 0 
 2 
 1 
 1 
 ... 
 0 
 64.0 
 102.0 
 80.0 
 87.0 
 47.0 
 3.0 
 28.0 
 1.8 
 2325.0 
 
 
 19 
 19 
 1 
 1 
 0 
 0 
 0 
 1 
 1 
 1 
 1 
 ... 
 0 
 68.0 
 108.0 
 72.0 
 84.0 
 97.0 
 6.6 
 55.0 
 3.8 
 1017.0 
 
 
 20 
 20 
 2 
 1 
 0 
 0 
 0 
 0 
 2 
 0 
 0 
 ... 
 0 
 74.0 
 130.0 
 80.0 
 97.0 
 104.0 
 7.7 
 54.0 
 4.0 
 1004.0 
 
 
 21 
 21 
 1 
 1 
 0 
 0 
 1 
 2 
 0 
 0 
 2 
 ... 
 0 
 81.0 
 116.0 
 82.0 
 93.0 
 43.0 
 3.5 
 26.0 
 2.1 
 2150.0 
 
 
 22 
 22 
 1 
 1 
 0 
 1 
 1 
 1 
 2 
 1 
 2 
 ... 
 0 
 45.0 
 108.0 
 74.0 
 85.0 
 101.0 
 4.5 
 53.0 
 2.4 
 2398.0 
 
 
 23 
 23 
 1 
 1 
 0 
 0 
 0 
 2 
 2 
 0 
 1 
 ... 
 2 
 75.0 
 120.0 
 66.0 
 84.0 
 59.0 
 4.4 
 29.0 
 2.2 
 1526.0 
 
 
 24 
 24 
 1 
 1 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 ... 
 0 
 72.0 
 114.0 
 64.0 
 81.0 
 127.0 
 9.1 
 60.0 
 4.3 
 708.0 
 
 
 25 
 25 
 1 
 0 
 0 
 0 
 0 
 1 
 1 
 1 
 2 
 ... 
 0 
 73.0 
 116.0 
 78.0 
 91.0 
 90.0 
 6.6 
 47.0 
 3.4 
 1098.0 
 
 
 26 
 26 
 2 
 0 
 0 
 0 
 1 
 2 
 0 
 0 
 1 
 ... 
 0 
 79.0 
 126.0 
 80.0 
 95.0 
 82.0 
 6.5 
 43.0 
 3.4 
 1172.0 
 
 
 27 
 27 
 1 
 2 
 0 
 0 
 1 
 0 
 1 
 0 
 2 
 ... 
 4 
 83.0 
 138.0 
 88.0 
 105.0 
 77.0 
 6.4 
 36.0 
 3.0 
 1316.0 
 
 
 28 
 28 
 2 
 0 
 0 
 2 
 1 
 2 
 2 
 2 
 2 
 ... 
 0 
 73.0 
 126.0 
 88.0 
 101.0 
 86.0 
 6.3 
 47.0 
 3.9 
 1277.0 
 
 
 29 
 29 
 1 
 0 
 0 
 0 
 0 
 1 
 2 
 1 
 1 
 ... 
 0 
 75.0 
 124.0 
 70.0 
 88.0 
 83.0 
 6.2 
 44.0 
 3.3 
 1134.0 
 
 
 30 
 30 
 2 
 2 
 0 
 1 
 2 
 2 
 2 
 1 
 2 
 ... 
 0 
 63.0 
 110.0 
 84.0 
 93.0 
 79.0 
 5.0 
 41.0 
 2.6 
 1481.0 
 
 
 31 
 31 
 1 
 1 
 0 
 1 
 0 
 1 
 2 
 0 
 2 
 

# Вилкоксон (Н)

# Критерий Вилкоксона для независимых выборок

In [6]:
def wilcoxon_ind(x: np.ndarray, y: np.ndarray, alternative: str = 'two-sided') -> Tuple[float, float]:    
    xy = np.concatenate((x, y))
    ranks = rankdata(xy)

    value_to_rank = dict(zip(xy, ranks))
    
    r1 = sum(value_to_rank[value] for value in x)

    n1 = len(x)
    n2 = len(y)

    u = r1 - n1 * (n1 + 1) / 2
    mean = n1 * n2 / 2
    var = mean / 6 * (n1 + n2 + 1)

    z = (u - mean) / np.sqrt(var)

    return z, calculate_p_value(z, distribution=norm, alternative=alternative)

In [7]:
x = np.array([38, 42, 55, 55, 66, 66, 68, 73, 77])
y = np.array([30, 38, 60, 69, 70, 72, 82, 84, 86, 89, 92])

print(*ranksums(x=x, y=y, alternative='two-sided'))
print(*wilcoxon_ind(x=x, y=y, alternative='two-sided'))

print(*ranksums(x=x, y=y, alternative='less'))
print(*wilcoxon_ind(x=x, y=y, alternative='less'))

print(*ranksums(x=x, y=y, alternative='greater'))
print(*wilcoxon_ind(x=x, y=y, alternative='greater'))

-1.5954480704349312 0.11061207374852304
-1.5954480704349312 0.11061207374852304
-1.5954480704349312 0.05530603687426152
-1.5954480704349312 0.05530603687426152
-1.5954480704349312 0.9446939631257385
-1.5954480704349312 0.9446939631257385


In [8]:
data_amb, data_dis = addicts_data[addicts_data.intpla == 1], addicts_data[addicts_data.intpla == 2]

data_amb

prcod 
 intpla 
 sex 
 age 
 educat 
 curwor 
 asi1_med 
 asi2_emp 
 asi3_alc 
 asi4_dr 
 ... 
 ha 
 se 
 cravin 
 rabdru 
 rubsex 
 gaf 
 bdi 
 sstati 
 end 
 endpo 
 
 
 
 
 0 
 4 
 1 
 0 
 18 
 1 
 1 
 0.19 
 0.70 
 0.120 
 0.30 
 ... 
 1.0 
 0.0 
 4.6 
 1.0 
 4 
 55.0 
 25.0 
 60 
 0.0 
 5.0 
 
 
 2 
 2 
 1 
 0 
 23 
 2 
 0 
 0.50 
 1.00 
 0.300 
 0.30 
 ... 
 0.0 
 0.0 
 9.5 
 6.0 
 1 
 45.0 
 29.0 
 55 
 0.0 
 2.0 
 
 
 3 
 4 
 1 
 0 
 20 
 2 
 1 
 0.00 
 0.80 
 0.050 
 0.26 
 ... 
 1.0 
 0.0 
 2.7 
 11.0 
 4 
 40.0 
 28.0 
 58 
 0.0 
 5.0 
 
 
 5 
 1 
 1 
 0 
 24 
 2 
 0 
 0.52 
 0.50 
 0.100 
 0.30 
 ... 
 0.0 
 0.0 
 10.0 
 3.0 
 2 
 41.0 
 33.0 
 68 
 0.0 
 2.0 
 
 
 6 
 3 
 1 
 0 
 31 
 2 
 0 
 0.00 
 1.00 
 0.088 
 0.42 
 ... 
 0.0 
 0.0 
 7.8 
 9.0 
 7 
 40.0 
 23.0 
 55 
 1.0 
 1.0 
 
 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 
 
 259 
 4 
 1 
 0 
 20 
 2 
 0 
 0.30 
 0.00 
 0.090 
 0.30 
 ... 
 0.0 
 0.0 
 3.8 
 14.0 
 7 
 41.0 
 18.0 
 45 
 1.0 
 1.0 
 
 
 263 
 4 
 1 
 0 
 20 
 2 
 1 
 0.40 
 0.77 
 0.200 
 0.30 
 ... 
 0.0 
 0.0 
 5.6 
 7.0 
 5 
 1.1 
 14.0 
 47 
 0.0 
 5.0 
 
 
 264 
 1 
 1 
 0 
 28 
 2 
 1 
 0.00 
 0.30 
 0.050 
 0.20 
 ... 
 0.0 
 0.0 
 1.3 
 4.0 
 4 
 60.0 
 13.0 
 50 
 1.0 
 1.0 
 
 
 271 
 4 
 1 
 0 
 22 
 2 
 0 
 0.00 
 0.50 
 0.320 
 0.30 
 ... 
 0.0 
 0.0 
 4.0 
 5.0 
 4 
 40.0 
 19.0 
 48 
 0.0 
 2.0 
 
 
 279 
 3 
 1 
 0 
 28 
 2 
 0 
 0.40 
 1.00 
 0.120 
 0.30 
 ... 
 0.0 
 0.0 
 10.0 
 10.0 
 5 
 48.0 
 26.0 
 62 
 1.0 
 1.0 
 
 
 
 141 rows × 27 columns

In [9]:
data_amb_alc = data_amb.asi3_alc.to_numpy()
data_dis_alc = data_dis.asi3_alc.to_numpy()

print(data_amb_alc.mean())
print(data_dis_alc.mean())
print()
print(*ranksums(x=data_amb_alc, y=data_dis_alc, alternative='two-sided'))
print(*wilcoxon_ind(x=data_amb_alc, y=data_dis_alc, alternative='two-sided'))

0.09891489361702129
0.06071223021582734

5.8395151504787055 5.235295581729013e-09
5.8395151504787055 5.235295581729013e-09


In [10]:
data_amb_leg = data_amb.asi5_leg.to_numpy()
data_dis_leg = data_dis.asi5_leg.to_numpy()

print(data_amb_leg.mean())
print(data_dis_leg.mean())
print()
print(*ranksums(x=data_amb_leg, y=data_dis_leg, alternative='two-sided'))
print(*wilcoxon_ind(x=data_amb_leg, y=data_dis_leg, alternative='two-sided'))

0.12196453900709221
0.18156115107913667

-0.509998100225074 0.6100527927471391
-0.509998100225074 0.6100527927471391


# Вилкоксон (З)

# Критерий Вилкоксона для зависимых выборок

In [11]:
def wilcoxon_paired(x: np.ndarray, y: np.ndarray, alternative: str = 'two-sided') -> Tuple[float, float, float]:
    d = x - y
    d = d[d != 0]

    count = len(d)
    ranks = rankdata(abs(d))

    s_minus = ranks[d < 0].sum()
    T = s_minus  # В scipy это значение зависит от альтернативной гипотезы

    mean = count * (count + 1) / 4
    variance = count * (count + 1) * (2 * count + 1) / 24

    # В scipy также есть корректировка на повторяющиеся значения
    statistics = (s_minus - mean) / np.sqrt(variance)

    return s_minus, statistics, calculate_p_value(statistics, distribution=norm, alternative=alternative)

In [12]:
x = np.array([68, 80, 92, 81, 70, 79, 78, 66, 57, 76])
y = np.array([60, 84, 87, 79, 74, 71, 72, 67, 57, 70])

# В scipy статистика зависит от альтернативной гипотезы
# + применяются поправки на повторяющиеся значения

print(*wilcoxon(x, y, mode='approx', alternative='two-sided'))
print(*wilcoxon_paired(x, y, alternative='two-sided'))

print(*wilcoxon(x, y, mode='approx', alternative='less'))
print(*wilcoxon_paired(x, y, alternative='less'))

print(*wilcoxon(x, y, mode='approx', alternative='greater'))
print(*wilcoxon_paired(x, y, alternative='greater'))

8.0 0.08500609446628643
8.0 -1.7178117455013677 0.08583095844428565
37.0 0.9574969527668568
8.0 -1.7178117455013677 0.042915479222142824
37.0 0.042503047233143215
8.0 -1.7178117455013677 0.9570845207778572


/opt/python/envs/default/lib/python3.8/site-packages/scipy/stats/morestats.py:3155: UserWarning: Sample size too small for normal approximation.
  warnings.warn("Sample size too small for normal approximation.")


In [13]:
x = np.array([87, 61, 98, 90, 93, 74, 83, 72, 81, 75, 83])
y = np.array([50, 45, 79, 90, 88, 65, 52, 79, 84, 61, 52])

# В scipy статистика зависит от альтернативной гипотезы
# + применяются поправки на повторяющиеся значения

print(*wilcoxon(x, y, mode='approx', alternative='two-sided'))
print(*wilcoxon_paired(x, y, alternative='two-sided'))

print(*wilcoxon(x, y, mode='approx', alternative='less'))
print(*wilcoxon_paired(x, y, alternative='less'))

print(*wilcoxon(x, y, mode='approx', alternative='greater'))
print(*wilcoxon_paired(x, y, alternative='greater'))

4.0 0.01653449266792266
4.0 -2.39534179975684 0.016604878103722735
51.0 0.9917327536660386
4.0 -2.39534179975684 0.008302439051861368
51.0 0.00826724633396133
4.0 -2.39534179975684 0.9916975609481387


In [14]:
alcohol_data_headache_1 = alcohol_data['headache.1'].to_numpy()
alcohol_data_headache_2 = alcohol_data['headache.2'].to_numpy()

print(alcohol_data_headache_1.mean())
print(alcohol_data_headache_2.mean())
print()
print(*wilcoxon(alcohol_data_headache_1, alcohol_data_headache_2, mode='approx', alternative='two-sided'))
print(*wilcoxon_paired(alcohol_data_headache_1, alcohol_data_headache_2, alternative='two-sided'))

0.4411764705882353
0.29411764705882354

24.0 0.19670560245894686
24.0 -1.1766968108291043 0.23931654122149526


In [15]:
alcohol_data_weakness_1 = alcohol_data['weakness.1'].to_numpy()
alcohol_data_weakness_2 = alcohol_data['weakness.2'].to_numpy()

print(alcohol_data_weakness_1.mean())
print(alcohol_data_weakness_2.mean())
print()
print(*wilcoxon(alcohol_data_weakness_1, alcohol_data_weakness_2, mode='approx', alternative='two-sided'))
print(*wilcoxon_paired(alcohol_data_weakness_1, alcohol_data_weakness_2, alternative='two-sided'))

1.3823529411764706
1.0294117647058822

43.5 0.02556159718726949
43.5 -2.072472364207749 0.03822141091463662


# Фридман (м-З)

# Критерий Фридмана для нескольких зависимых выборок 

In [16]:
def friedman_multipaired(array: np.ndarray) -> Tuple[float, float]:
    n, c = array.shape

    ranks = np.apply_along_axis(lambda row: rankdata(row), 1, array)

    column_rank_sums = np.apply_along_axis(lambda row: row.sum(), 0, ranks)
    r_mean = column_rank_sums / n
    r = (c + 1) / 2

    # Корректировки не было на паре
    ties = 0
    for row in ranks:
        _, repnum = np.unique(row, return_counts=True)
        for t in repnum:
            ties += t * (t*t - 1)
    ties_correction = 1 - ties / (c*(c*c - 1)*n)

    statistics = 12 * n / (c * (c + 1)) * ((r_mean - r) ** 2).sum() / ties_correction

    return statistics, calculate_p_value(statistics, distribution=chi2, alternative='greater', df=c - 1)

In [17]:
x = np.array([
    [52, 45, 38],
    [63, 79, 50],
    [45, 57, 39],
    [53, 51, 43],
    [47, 50, 56],
    [62, 72, 49],
    [49, 52, 40],
])

print(*friedmanchisquare(*x.T))
print(*friedman_multipaired(x))

6.0 0.04978706836786395
6.0 0.04978706836786395


In [18]:
alcohol_data_headache = alcohol_data[['headache.1', 'headache.2', 'headache.9']]
alcohol_data_headache = alcohol_data_headache.dropna().to_numpy()

print(alcohol_data_headache[:, 0].mean())
print(alcohol_data_headache[:, 1].mean())
print(alcohol_data_headache[:, 2].mean())
print()
print(*friedmanchisquare(*alcohol_data_headache.T))
print(*friedman_multipaired(alcohol_data_headache))

0.3939393939393939
0.30303030303030304
0.030303030303030304

12.933333333333408 0.0015543984350842451
12.933333333333321 0.0015543984350843123


In [19]:
alcohol_data_co = alcohol_data[['CO.1', 'CO.2', 'CO.9']]
alcohol_data_co = alcohol_data_co.dropna().to_numpy()

print(alcohol_data_co[:, 0].mean())
print(alcohol_data_co[:, 1].mean())
print(alcohol_data_co[:, 2].mean())
print()
print(*friedmanchisquare(*alcohol_data_co.T))
print(*friedman_multipaired(alcohol_data_co))

5.783870967741936
4.838709677419354
5.816129032258065

8.999999999999961 0.011108996538242525
8.999999999999995 0.011108996538242339


# Краскел-Уоллис (м-Н)

# Критерий Краскела-Уоллиса для нескольких независимых выборок 

In [20]:
def kruskal_multi_ind(*samples) -> Tuple[float, float]:
    united = np.concatenate(samples)
    n = len(united)

    ranks = rankdata(united)
    value_to_rank = dict(zip(united, ranks))

    statisitcs = sum(
        sum(value_to_rank[value] for value in sample) ** 2 / len(sample)
        for sample in samples
    )

    statisitcs *= 12 / (n * (n + 1))
    statisitcs -= 3 * (n + 1)

    _, counts = np.unique(united, return_counts=True)
    counts = counts[counts > 1]

    ties_correction = 1 - sum((count ** 3 - count) / (n ** 3 - n) for count in counts)

    statisitcs /= ties_correction

    return statisitcs, calculate_p_value(statisitcs, distribution=chi2, alternative='greater', df=len(samples) - 1)

In [21]:
x = [1, 3, 5, 7, 9]
y = [2, 4, 6, 8, 10]

print(*kruskal(x, y))
print(*kruskal_multi_ind(x, y))

0.2727272727272734 0.6015081344405895
0.2727272727272734 0.6015081344405895


In [22]:
x = [1, 1, 1]
y = [2, 2, 2]
z = [2, 2]

print(*kruskal(x, y, z))
print(*kruskal_multi_ind(x, y, z))

7.0 0.0301973834223185
7.0 0.0301973834223185


In [23]:
data_eight, data_school, data_incompl_higher, data_higher = (
    addicts_data[addicts_data.educat == 1],
    addicts_data[addicts_data.educat == 2],
    addicts_data[addicts_data.educat == 3],
    addicts_data[addicts_data.educat == 4],
)

data_eight

prcod 
 intpla 
 sex 
 age 
 educat 
 curwor 
 asi1_med 
 asi2_emp 
 asi3_alc 
 asi4_dr 
 ... 
 ha 
 se 
 cravin 
 rabdru 
 rubsex 
 gaf 
 bdi 
 sstati 
 end 
 endpo 
 
 
 
 
 0 
 4 
 1 
 0 
 18 
 1 
 1 
 0.19 
 0.70 
 0.12 
 0.30 
 ... 
 1.0 
 0.0 
 4.6 
 1.0 
 4 
 55.0 
 25.0 
 60 
 0.0 
 5.0 
 
 
 11 
 2 
 1 
 1 
 19 
 1 
 1 
 0.70 
 0.19 
 0.10 
 0.30 
 ... 
 0.0 
 0.0 
 5.6 
 6.0 
 5 
 45.0 
 24.0 
 45 
 1.0 
 1.0 
 
 
 18 
 3 
 1 
 0 
 24 
 1 
 1 
 0.60 
 0.25 
 0.16 
 0.30 
 ... 
 0.0 
 0.0 
 8.2 
 12.0 
 8 
 51.0 
 18.0 
 44 
 1.0 
 1.0 
 
 
 21 
 2 
 1 
 1 
 19 
 1 
 0 
 0.54 
 1.00 
 0.11 
 0.30 
 ... 
 0.0 
 0.0 
 2.5 
 8.0 
 8 
 45.0 
 42.0 
 46 
 0.0 
 2.0 
 
 
 29 
 1 
 1 
 1 
 23 
 1 
 0 
 0.53 
 0.90 
 0.23 
 0.30 
 ... 
 0.0 
 0.0 
 5.8 
 6.0 
 5 
 45.0 
 24.0 
 50 
 1.0 
 1.0 
 
 
 49 
 1 
 1 
 0 
 23 
 1 
 1 
 0.58 
 0.19 
 0.11 
 0.32 
 ... 
 1.0 
 0.0 
 2.3 
 6.0 
 7 
 50.0 
 20.0 
 72 
 0.0 
 5.0 
 
 
 54 
 2 
 1 
 0 
 19 
 1 
 0 
 0.00 
 1.00 
 0.01 
 0.29 
 ... 
 0.0 
 0.0 
 0.9 
 14.0 
 5 
 40.0 
 31.0 
 56 
 0.0 
 2.0 
 
 
 63 
 3 
 1 
 0 
 27 
 1 
 1 
 0.83 
 0.69 
 0.08 
 0.30 
 ... 
 0.0 
 0.0 
 4.7 
 8.0 
 4 
 65.0 
 21.0 
 33 
 0.0 
 2.0 
 
 
 106 
 3 
 1 
 0 
 23 
 1 
 1 
 0.00 
 0.94 
 0.22 
 0.25 
 ... 
 0.0 
 0.0 
 4.8 
 12.0 
 6 
 40.0 
 19.0 
 55 
 0.0 
 5.0 
 
 
 115 
 3 
 1 
 0 
 24 
 1 
 1 
 0.70 
 0.20 
 0.10 
 0.30 
 ... 
 0.0 
 0.0 
 6.0 
 4.0 
 1 
 50.0 
 19.0 
 52 
 0.0 
 6.0 
 
 
 120 
 2 
 2 
 1 
 25 
 1 
 0 
 0.39 
 1.00 
 0.00 
 0.28 
 ... 
 0.0 
 0.0 
 8.4 
 7.0 
 6 
 41.0 
 25.0 
 50 
 0.0 
 2.0 
 
 
 131 
 3 
 2 
 0 
 17 
 1 
 0 
 0.39 
 1.00 
 0.01 
 0.26 
 ... 
 1.0 
 0.0 
 3.5 
 16.0 
 3 
 51.0 
 20.0 
 56 
 0.0 
 2.0 
 
 
 141 
 1 
 1 
 0 
 23 
 1 
 1 
 0.20 
 0.70 
 0.12 
 0.30 
 ... 
 0.0 
 0.0 
 6.6 
 4.0 
 5 
 55.0 
 14.0 
 43 
 1.0 
 1.0 
 
 
 165 
 2 
 1 
 0 
 24 
 1 
 1 
 0.40 
 0.20 
 0.08 
 0.24 
 ... 
 0.0 
 0.0 
 9.0 
 14.0 
 4 
 41.0 
 18.0 
 59 
 1.0 
 1.0 
 
 
 202 
 2 
 2 
 0 
 17 
 1 
 0 
 0.00 
 1.00 
 0.00 
 0.23 
 ... 
 0.0 
 0.0 
 0.3 
 1.0 
 3 
 65.0 
 4.0 
 35 
 1.0 
 1.0 
 
 
 205 
 2 
 2 
 0 
 26 
 1 
 0 
 0.48 
 1.00 
 0.02 
 0.24 
 ... 
 0.0 
 0.0 
 0.0 
 9.0 
 3 
 41.0 
 16.0 
 47 
 0.0 
 3.0 
 
 
 212 
 4 
 1 
 0 
 19 
 1 
 0 
 0.51 
 1.00 
 0.26 
 0.30 
 ... 
 0.0 
 0.0 
 3.5 
 3.0 
 1 
 45.0 
 43.0 
 72 
 0.0 
 5.0 
 
 
 229 
 1 
 2 
 0 
 17 
 1 
 0 
 0.00 
 1.00 
 0.01 
 0.21 
 ... 
 0.0 
 1.0 
 5.0 
 7.0 
 5 
 41.0 
 7.0 
 30 
 0.0 
 5.0 
 
 
 246 
 1 
 2 
 0 
 28 
 1 
 0 
 0.52 
 1.00 
 0.05 
 0.18 
 ... 
 0.0 
 0.0 
 0.2 
 1.0 
 4 
 41.0 
 23.0 
 45 
 1.0 
 1.0 
 
 
 257 
 2 
 1 
 0 
 23 
 1 
 0 
 0.53 
 1.00 
 0.08 
 0.30 
 ... 
 0.0 
 0.0 
 5.7 
 8.0 
 2 
 51.0 
 25.0 
 48 
 0.0 
 2.0 
 
 
 266 
 1 
 2 
 0 
 19 
 1 
 0 
 0.39 
 1.00 
 0.00 
 0.32 
 ... 
 1.0 
 0.0 
 6.5 
 7.0 
 7 
 41.0 
 24.0 
 45 
 0.0 
 5.0 
 
 
 
 21 rows × 27 columns

In [24]:
data_eight_emp = data_eight.asi2_emp.to_numpy()
data_school_emp = data_school.asi2_emp.to_numpy()
data_incompl_higher_emp = data_incompl_higher.asi2_emp.to_numpy()
data_higher_emp = data_higher.asi2_emp.to_numpy()

data_school_emp = data_school_emp[~np.isnan(data_school_emp)]
data_incompl_higher_emp = data_incompl_higher_emp[~np.isnan(data_incompl_higher_emp)]

print(data_eight_emp.mean())
print(data_school_emp.mean())
print(data_incompl_higher_emp.mean())
print(data_higher_emp.mean())
print()
print(*kruskal(data_eight_emp, data_school_emp, data_incompl_higher_emp, data_higher_emp))
print(*kruskal_multi_ind(data_eight_emp, data_school_emp, data_incompl_higher_emp, data_higher_emp))

0.76
0.8074660633484162
0.6618518518518519
0.6344444444444445

8.921122877272833 0.0303581927931991
8.921122877272833 0.0303581927931991


In [25]:
data_eight_soc = data_eight.asi6_soc.to_numpy()
data_school_soc = data_school.asi6_soc.to_numpy()
data_incompl_higher_soc = data_incompl_higher.asi6_soc.to_numpy()
data_higher_soc = data_higher.asi6_soc.to_numpy()

print(data_eight_soc.mean())
print(data_school_soc.mean())
print(data_incompl_higher_soc.mean())
print(data_higher_soc.mean())
print()
print(*kruskal(data_eight_soc, data_school_soc, data_incompl_higher_soc, data_higher_soc))
print(*kruskal_multi_ind(data_eight_soc, data_school_soc, data_incompl_higher_soc, data_higher_soc))

0.3761904761904762
0.4213828828828829
0.4035714285714286
0.4788888888888889

1.3650417008259736 0.7137492145830313
1.3650417008259736 0.7137492145830313


# Медианный тест (м-Н)

# Медианный тест для нескольких независимых выборок

In [26]:
def my_median_test(*samples) -> Tuple[float, float, np.ndarray, np.ndarray]:
    united = np.concatenate(samples)
    median = np.median(united)
    n = len(united)

    table = np.zeros((2, len(samples)), dtype=int)
    for k, sample in enumerate(samples):
        table[0, k] = np.count_nonzero(sample > median)
        table[1, k] = np.count_nonzero(sample <= median)

    row_sums = table.sum(axis=1)
    column_sums = table.sum(axis=0)

    statistics = 0
    for j, column in enumerate(table.T):
        frac = (column - column_sums[j] * row_sums / n) ** 2
        frac /= column_sums[j] * row_sums / n
        statistics += frac.sum()

    return (
        statistics,
        calculate_p_value(statistics, distribution=chi2, alternative='greater', df=len(samples) - 1),
        median,
        table,
    )

In [27]:
g1 = [10, 14, 14, 18, 20, 22, 24, 25, 31, 31, 32, 39, 43, 43, 48, 49]
g2 = [28, 30, 31, 33, 34, 35, 36, 40, 44, 55, 57, 61, 91, 92, 99]
g3 = [0, 3, 9, 22, 23, 25, 25, 33, 34, 34, 40, 45, 46, 48, 62, 67, 84]

print(*median_test(g1, g2, g3), sep='\n')
print(*my_median_test(g1, g2, g3), sep='\n')

4.141505553270259
0.12609082774093244
34.0
[[ 5 10  7]
 [11  5 10]]
4.141505553270259
0.12609082774093244
34.0
[[ 5 10  7]
 [11  5 10]]


In [28]:
print(data_eight_emp.mean())
print(data_school_emp.mean())
print(data_incompl_higher_emp.mean())
print(data_higher_emp.mean())
print()
print(*median_test(data_eight_emp, data_school_emp, data_incompl_higher_emp, data_higher_emp), sep='\n', end='\n\n')
print(*my_median_test(data_eight_emp, data_school_emp, data_incompl_higher_emp, data_higher_emp), sep='\n', end='\n\n')

0.76
0.8074660633484162
0.6618518518518519
0.6344444444444445

6.753860518566401
0.08017092006384198
0.915
[[ 12 116   9   2]
 [  9 105  18   7]]

6.753860518566401
0.08017092006384198
0.915
[[ 12 116   9   2]
 [  9 105  18   7]]



In [29]:
print(data_eight_soc.mean())
print(data_school_soc.mean())
print(data_incompl_higher_soc.mean())
print(data_higher_soc.mean())
print()
print(*median_test(data_eight_soc, data_school_soc, data_incompl_higher_soc, data_higher_soc), sep='\n', end='\n\n')
print(*my_median_test(data_eight_soc, data_school_soc, data_incompl_higher_soc, data_higher_soc), sep='\n', end='\n\n')

0.3761904761904762
0.4213828828828829
0.4035714285714286
0.4788888888888889

1.1689571095663251
0.7604588964596212
0.43
[[  9 113  12   5]
 [ 12 109  16   4]]

1.1689571095663251
0.7604588964596212
0.43
[[  9 113  12   5]
 [ 12 109  16   4]]

